name: Super Serious Commit Generator

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every night
    # cron syntax: 
    # min hour date-of-month month day-of-week 
    # / = step values, ? = wildcard, - = range, ,=multiple values, *=all possible matches
  workflow_dispatch:

jobs:
  make-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Make a serious change
      - name: Make serious change
        run: |
          echo "Serious commit at $(date)" >> serious_file.txt

      # Commit and push the change
      - name: Commit and push
        run: |
          git config --global user.name "user-name"
          git config --global user.email "email"
          git add .
          git commit -m "Automated serious commit $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
